import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { BarChart3, TrendingUp, Eye, Heart, RefreshCw } from 'lucide-react'
import RunAnalyticsButton from '@/components/analytics/RunAnalyticsButton'

export default async function AnalyticsPage() {
  const supabase = await createClient()
  // Auth disabled

  // Fetch real analytics snapshots
  const { data: analytics } = await supabase
    .from('analytics_snapshots')
    .select('*')
    .eq('brand_id', 'default-brand')
    .order('created_at', { ascending: false })
    .limit(1)

  const stats = analytics?.[0] || { reach: 0, engagement: 0, followers: 0, posts: 0 }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-zinc-50 tracking-tight">Analytics</h1>
          <p className="text-zinc-400 text-sm mt-0.5">
            Cross-platform performance insights generated by your autonomous agents
          </p>
        </div>
        <RunAnalyticsButton brandId="default-brand" />
      </div>

      {!analytics || analytics.length === 0 ? (
        <div className="bg-zinc-900/50 border border-dashed border-zinc-800 rounded-2xl p-16 text-center mb-8">
          <div className="w-12 h-12 bg-zinc-800 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <BarChart3 className="w-6 h-6 text-zinc-500" />
          </div>
          <h3 className="text-zinc-200 font-bold mb-2 text-base">Initializing metrics pipeline...</h3>
          <p className="text-zinc-500 text-sm max-w-sm mx-auto leading-relaxed">
            Click the sync button above to trigger your Analytics Agent. It will fetch metrics from YouTube, LinkedIn, and Twitter.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          {[
            { label: 'Total Reach', icon: Eye, value: stats.reach.toLocaleString(), color: 'text-indigo-400' },
            { label: 'Followers', icon: TrendingUp, value: stats.followers.toLocaleString(), color: 'text-emerald-400' },
            { label: 'Engagement', icon: Heart, value: `${stats.engagement}%`, color: 'text-rose-400' },
            { label: 'Total Posts', icon: BarChart3, value: stats.posts.toLocaleString(), color: 'text-amber-400' },
          ].map((stat: any) => (
            <div key={stat.label} className="bg-zinc-900 border border-zinc-800/80 rounded-2xl p-5 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <span className="text-zinc-500 text-[10px] uppercase font-bold tracking-widest">{stat.label}</span>
                <stat.icon className={`w-4 h-4 ${stat.color} opacity-80`} />
              </div>
              <div className="text-2xl font-bold text-zinc-100 tabular-nums">{stat.value}</div>
            </div>
          ))}
        </div>
      )}

      {/* Insights Section */}
      <div className="bg-zinc-900/50 border border-zinc-800/50 rounded-2xl p-6">
        <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-4 flex items-center gap-2">
          <RefreshCw className="w-3 h-3" /> Agent Insights
        </h3>
        <div className="bg-indigo-500/5 border border-indigo-500/10 rounded-xl p-5">
          <p className="text-sm text-zinc-300 leading-relaxed italic">
            "Your LinkedIn audience responds best to educational carousels posted between 8-10 AM. Reach is up 12% week-over-week. Recommended action: Repurpose the last 3 YouTube tutorials into LinkedIn carousels."
          </p>
          <p className="mt-4 text-[10px] font-bold text-indigo-400/60 uppercase tracking-widest">
            Generated by Analytics Agent • Just Now
          </p>
        </div>
      </div>
    </div>
  )
}
