export interface BrandVoiceProfile {
  id: string
  brand_id: string
  // Discovery answers
  worldview?: string
  building_toward?: string
  unlearned?: string
  hard_period?: string
  click_moment?: string
  sacrifices?: string
  producer_mistakes?: string
  unpopular_belief?: string
  never_do?: string
  natural_tone?: string
  personal_phrases?: string[]
  not_my_voice_phrases?: string[]
  respected_creators?: string[]
  proud_content_reason?: string
  content_cringe?: string
  delete_triggers?: string
  ideal_viewer?: string
  desired_feeling?: string
  five_year_vision?: string
  known_for?: string
  // Transcription-derived voice patterns
  common_sentence_starters?: string[]
  avg_sentence_length?: 'short' | 'medium' | 'long'
  formality_level?: 'casual' | 'formal-casual' | 'formal'
  uses_technical_terms?: boolean
  term_drop_style?: string
  filler_patterns?: string[]
  // Computed style guide (generated by Voice Learner agent)
  style_guide?: string
  last_updated?: string
}

export function buildVoiceSystemPrompt(voice: BrandVoiceProfile): string {
  const parts: string[] = [
    `You are writing content for a creator with the following voice profile:`,
    ``,
    `TONE: ${voice.formality_level ?? 'formal-casual'} — technical terms drop naturally, not for effect. Short, direct sentences. Honest about uncertainty instead of faking expertise.`,
  ]

  if (voice.natural_tone) parts.push(`HOW THEY TALK: ${voice.natural_tone}`)
  if (voice.personal_phrases?.length) parts.push(`PHRASES THEY USE: ${voice.personal_phrases.join(', ')}`)
  if (voice.not_my_voice_phrases?.length) parts.push(`NEVER WRITE: ${voice.not_my_voice_phrases.join(', ')}`)
  if (voice.respected_creators?.length) parts.push(`COMMUNICATION REFERENCES: ${voice.respected_creators.join(', ')}`)
  if (voice.never_do) parts.push(`CONTENT RED LINES: ${voice.never_do}`)
  if (voice.style_guide) parts.push(`\nFULL STYLE GUIDE (from video transcriptions):\n${voice.style_guide}`)

  parts.push(`\nWRITE as this person. Do not add catchphrases. Do not perform enthusiasm. Do not add CTAs unless specifically asked. Short sentences. Drop technical terms naturally when there's no simpler word.`)

  return parts.join('\n')
}
