// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/brands" | "/brands/[brandId]" | "/brands/new" | "/calendar" | "/dashboard" | "/ideate" | "/login" | "/pipeline" | "/register" | "/repurpose" | "/settings/api-keys" | "/settings/connections"
type AppRouteHandlerRoutes = "/api/agency-lead" | "/api/agents/analytics" | "/api/agents/brainstorm" | "/api/agents/content-writer" | "/api/agents/flesh-out" | "/api/agents/idea-generator" | "/api/agents/publisher" | "/api/agents/scheduler" | "/api/agents/trend-scout" | "/api/agents/video-repurposer" | "/api/agents/voice-learner" | "/api/carousel/render-slide" | "/api/debug" | "/api/health" | "/api/oauth/instagram" | "/api/oauth/instagram/callback" | "/api/oauth/tiktok" | "/api/oauth/tiktok/callback" | "/api/oauth/twitter" | "/api/oauth/twitter/callback" | "/api/oauth/youtube" | "/api/oauth/youtube/callback" | "/api/run-agent" | "/api/run-agent/logs" | "/api/seed-brand" | "/api/video/extract-frames" | "/api/video/upload"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/agency-lead": {}
  "/api/agents/analytics": {}
  "/api/agents/brainstorm": {}
  "/api/agents/content-writer": {}
  "/api/agents/flesh-out": {}
  "/api/agents/idea-generator": {}
  "/api/agents/publisher": {}
  "/api/agents/scheduler": {}
  "/api/agents/trend-scout": {}
  "/api/agents/video-repurposer": {}
  "/api/agents/voice-learner": {}
  "/api/carousel/render-slide": {}
  "/api/debug": {}
  "/api/health": {}
  "/api/oauth/instagram": {}
  "/api/oauth/instagram/callback": {}
  "/api/oauth/tiktok": {}
  "/api/oauth/tiktok/callback": {}
  "/api/oauth/twitter": {}
  "/api/oauth/twitter/callback": {}
  "/api/oauth/youtube": {}
  "/api/oauth/youtube/callback": {}
  "/api/run-agent": {}
  "/api/run-agent/logs": {}
  "/api/seed-brand": {}
  "/api/video/extract-frames": {}
  "/api/video/upload": {}
  "/brands": {}
  "/brands/[brandId]": { "brandId": string; }
  "/brands/new": {}
  "/calendar": {}
  "/dashboard": {}
  "/ideate": {}
  "/login": {}
  "/pipeline": {}
  "/register": {}
  "/repurpose": {}
  "/settings/api-keys": {}
  "/settings/connections": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
