// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/brands/[brandId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/[brandId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/brands/[brandId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/brands/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/brands/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ideate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ideate">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ideate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/repurpose/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repurpose">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/repurpose/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/api-keys">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/connections">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency-lead">> = Specific
  const handler = {} as typeof import("../../app/api/agency-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/agents/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/brainstorm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/brainstorm">> = Specific
  const handler = {} as typeof import("../../app/api/agents/brainstorm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/content-writer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/content-writer">> = Specific
  const handler = {} as typeof import("../../app/api/agents/content-writer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/flesh-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/flesh-out">> = Specific
  const handler = {} as typeof import("../../app/api/agents/flesh-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/idea-generator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/idea-generator">> = Specific
  const handler = {} as typeof import("../../app/api/agents/idea-generator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/publisher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/publisher">> = Specific
  const handler = {} as typeof import("../../app/api/agents/publisher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/scheduler/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/scheduler">> = Specific
  const handler = {} as typeof import("../../app/api/agents/scheduler/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/trend-scout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/trend-scout">> = Specific
  const handler = {} as typeof import("../../app/api/agents/trend-scout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/video-repurposer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/video-repurposer">> = Specific
  const handler = {} as typeof import("../../app/api/agents/video-repurposer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/voice-learner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/voice-learner">> = Specific
  const handler = {} as typeof import("../../app/api/agents/voice-learner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/carousel/render-slide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carousel/render-slide">> = Specific
  const handler = {} as typeof import("../../app/api/carousel/render-slide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/instagram/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/instagram/callback">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/instagram/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/instagram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/instagram">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/instagram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/tiktok/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/tiktok/callback">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/tiktok/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/tiktok/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/tiktok">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/tiktok/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/twitter/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/twitter/callback">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/twitter/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/twitter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/twitter">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/twitter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/youtube/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/youtube/callback">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/youtube/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/oauth/youtube/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/youtube">> = Specific
  const handler = {} as typeof import("../../app/api/oauth/youtube/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/run-agent/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-agent/logs">> = Specific
  const handler = {} as typeof import("../../app/api/run-agent/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/run-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-agent">> = Specific
  const handler = {} as typeof import("../../app/api/run-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/seed-brand/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-brand">> = Specific
  const handler = {} as typeof import("../../app/api/seed-brand/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/video/extract-frames/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/extract-frames">> = Specific
  const handler = {} as typeof import("../../app/api/video/extract-frames/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/video/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/upload">> = Specific
  const handler = {} as typeof import("../../app/api/video/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
