-- Add platform_captions to content_drafts
ALTER TABLE content_drafts 
ADD COLUMN IF NOT EXISTS platform_captions JSONB DEFAULT '{}';

-- Add comment for clarity
COMMENT ON COLUMN content_drafts.platform_captions IS 'A dictionary of platform-specific captions generated by the Content Writer agent.';
